
export type BotState = 
//MENU
| 'START'
| 'MENU' 
//IMAGE
| 'MENU_IMAGE'
| 'IMAGE_GENERATE'
| 'IMAGE_EDIT'
| 'IMAGE_WAIT_FOR_TEXT'
| 'IMAGE_WAIT_FOR_USER_UPLOAD_IMAGE'
//VIDEO
| 'MENU_VIDEO'
| 'VIDEO_CUT'
| 'VIDEO_GENERATE'
| 'VIDEO_EDIT'
| 'VIDEO_WAIT_FOR_TEXT'
| 'VIDEO_WAIT_FOR_USER_UPLOAD_VIDEO'